# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc6b4eee8d5e49cf998da60124f6f1fec8f9efaf5f66f569f3b2d009cce702087b9b48dec277da7a436161488af7213ce9cdac656ccd42db5fd4c3764e139117

test:
  secret_key_base: 5ad23029ebfa7b5670ab0d90147199213a69ebbc5c69447a765df70d5840eecb192b2062e17df8a81eebbe041b8e6ecf6bc74197426d5226a954cbcb5583dece

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
